// <auto-generated />
using System;
using Demo.Website.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Website.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230826133310_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Website.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("CURRENT_USER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(4);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1998, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rschrader0@php.net",
                            FirstName = "Raimondo",
                            LastName = "Schrader",
                            Telephone = "+62 902 262 5292"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1912, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bhilliam1@myspace.com",
                            FirstName = "Berty",
                            LastName = "Hilliam",
                            Telephone = "+51 986 441 8160"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1956, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jkonke2@bloomberg.com",
                            FirstName = "Jerrilyn",
                            LastName = "Konke",
                            Telephone = "+62 551 746 6178"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1988, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ktendahl3@spiegel.de",
                            FirstName = "Katha",
                            LastName = "Tendahl",
                            Telephone = "+212 694 360 6985"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1986, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mfritchley4@plala.or.jp",
                            FirstName = "Maurita",
                            LastName = "Fritchley",
                            Telephone = "+234 967 538 4108"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1969, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jkelcey5@angelfire.com",
                            FirstName = "Jeralee",
                            LastName = "Kelcey",
                            Telephone = "+63 308 341 5269"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1961, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hdyott6@ezinearticles.com",
                            FirstName = "Hamel",
                            LastName = "Dyott",
                            Telephone = "+86 127 614 5543"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2000, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hdorgon7@de.vu",
                            FirstName = "Harrie",
                            LastName = "Dorgon",
                            Telephone = "+54 208 740 5477"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2001, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bheaps8@noaa.gov",
                            FirstName = "Basilio",
                            LastName = "Heaps",
                            Telephone = "+63 956 371 7412"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1951, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lfaithfull9@rakuten.co.jp",
                            FirstName = "Lani",
                            LastName = "Faithfull",
                            Telephone = "+86 706 298 4155"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1983, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ocharlea@ebay.com",
                            FirstName = "Oriana",
                            LastName = "Charle",
                            Telephone = "+57 940 604 4834"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1967, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jbristerb@tamu.edu",
                            FirstName = "Jelene",
                            LastName = "Brister",
                            Telephone = ""
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1904, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nsigwardc@chronoengine.com",
                            FirstName = "Nobe",
                            LastName = "Sigward",
                            Telephone = "+1 370 112 2088"
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1969, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mbeaumand@mozilla.org",
                            FirstName = "Meta",
                            LastName = "Beauman",
                            Telephone = "+63 993 312 9156"
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1960, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "aroantreee@techcrunch.com",
                            FirstName = "Ari",
                            LastName = "Roantree",
                            Telephone = "+55 446 190 3704"
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(1953, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rdowdingf@hhs.gov",
                            FirstName = "Robinett",
                            LastName = "Dowding",
                            Telephone = ""
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(1903, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ajakog@example.com",
                            FirstName = "Amitie",
                            LastName = "Jako",
                            Telephone = "+7 404 858 2968"
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(1950, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "fstormonthh@1688.com",
                            FirstName = "Fidelia",
                            LastName = "Stormonth",
                            Telephone = "+976 562 493 2663"
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(1967, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "cgreigi@webs.com",
                            FirstName = "Chlo",
                            LastName = "Greig",
                            Telephone = "+7 831 396 7081"
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(1919, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bspencersj@uol.com.br",
                            FirstName = "Beverlie",
                            LastName = "Spencers",
                            Telephone = "+86 239 716 4825"
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(1950, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "cgarrattleyk@miibeian.gov.cn",
                            FirstName = "Chico",
                            LastName = "Garrattley",
                            Telephone = "+502 918 317 6571"
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(1970, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ncobbinl@yale.edu",
                            FirstName = "Noak",
                            LastName = "Cobbin",
                            Telephone = "+223 865 769 7812"
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(1914, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mnyssenm@sciencedirect.com",
                            FirstName = "Madalyn",
                            LastName = "Nyssen",
                            Telephone = "+55 413 322 8299"
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(1921, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "agiblingn@360.cn",
                            FirstName = "Andonis",
                            LastName = "Gibling",
                            Telephone = "+62 708 533 2017"
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(1933, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "gelacoateo@noaa.gov",
                            FirstName = "Gale",
                            LastName = "Elacoate",
                            Telephone = "+30 577 440 0552"
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateTime(1904, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mrisdalep@desdev.cn",
                            FirstName = "Maribel",
                            LastName = "Risdale",
                            Telephone = "+7 635 324 5719"
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateTime(1919, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ldochonq@hibu.com",
                            FirstName = "Lionel",
                            LastName = "Dochon",
                            Telephone = "+57 290 571 2109"
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateTime(1956, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "cvondrysr@wikipedia.org",
                            FirstName = "Candi",
                            LastName = "Vondrys",
                            Telephone = "+55 962 518 8471"
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateTime(1961, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hjesses@mapy.cz",
                            FirstName = "Herby",
                            LastName = "Jesse",
                            Telephone = "+380 567 163 9206"
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateTime(1901, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rmaccostyt@4shared.com",
                            FirstName = "Reinhard",
                            LastName = "MacCosty",
                            Telephone = "+380 968 576 0210"
                        },
                        new
                        {
                            Id = 31,
                            DateOfBirth = new DateTime(1979, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jpedroniu@cdc.gov",
                            FirstName = "Janice",
                            LastName = "Pedroni",
                            Telephone = "+51 742 906 1935"
                        },
                        new
                        {
                            Id = 32,
                            DateOfBirth = new DateTime(1928, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "smaroneyv@ucoz.ru",
                            FirstName = "Spense",
                            LastName = "Maroney",
                            Telephone = "+62 522 171 4877"
                        },
                        new
                        {
                            Id = 33,
                            DateOfBirth = new DateTime(1994, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ctregidgow@ca.gov",
                            FirstName = "Connie",
                            LastName = "Tregidgo",
                            Telephone = "+47 586 392 6223"
                        },
                        new
                        {
                            Id = 34,
                            DateOfBirth = new DateTime(1942, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "scretneyx@stanford.edu",
                            FirstName = "Shermie",
                            LastName = "Cretney",
                            Telephone = "+54 405 388 7430"
                        },
                        new
                        {
                            Id = 35,
                            DateOfBirth = new DateTime(1989, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mbriony@princeton.edu",
                            FirstName = "Mel",
                            LastName = "Brion",
                            Telephone = "+62 945 169 6174"
                        },
                        new
                        {
                            Id = 36,
                            DateOfBirth = new DateTime(1913, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ejannaschz@arstechnica.com",
                            FirstName = "Esta",
                            LastName = "Jannasch",
                            Telephone = "+33 216 530 0485"
                        },
                        new
                        {
                            Id = 37,
                            DateOfBirth = new DateTime(1978, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lcastangia10@economist.com",
                            FirstName = "Linc",
                            LastName = "Castangia",
                            Telephone = "+385 888 878 1806"
                        },
                        new
                        {
                            Id = 38,
                            DateOfBirth = new DateTime(2002, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hregelous11@engadget.com",
                            FirstName = "Humbert",
                            LastName = "Regelous",
                            Telephone = "+998 391 616 6178"
                        },
                        new
                        {
                            Id = 39,
                            DateOfBirth = new DateTime(1932, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kschimank12@instagram.com",
                            FirstName = "Kellen",
                            LastName = "Schimank",
                            Telephone = "+86 242 141 1499"
                        },
                        new
                        {
                            Id = 40,
                            DateOfBirth = new DateTime(1909, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ssore13@ox.ac.uk",
                            FirstName = "Sax",
                            LastName = "Sore",
                            Telephone = "+351 134 716 0893"
                        },
                        new
                        {
                            Id = 41,
                            DateOfBirth = new DateTime(1914, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "oshank14@ovh.net",
                            FirstName = "Orbadiah",
                            LastName = "Shank",
                            Telephone = "+356 946 978 4485"
                        },
                        new
                        {
                            Id = 42,
                            DateOfBirth = new DateTime(1917, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bronald15@youtu.be",
                            FirstName = "Brok",
                            LastName = "Ronald",
                            Telephone = ""
                        },
                        new
                        {
                            Id = 43,
                            DateOfBirth = new DateTime(1965, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hbraddick16@domainmarket.com",
                            FirstName = "Hendrick",
                            LastName = "Braddick",
                            Telephone = "+592 715 336 9142"
                        },
                        new
                        {
                            Id = 44,
                            DateOfBirth = new DateTime(1913, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "glilford17@pbs.org",
                            FirstName = "Gilberto",
                            LastName = "Lilford",
                            Telephone = "+82 109 639 2236"
                        },
                        new
                        {
                            Id = 45,
                            DateOfBirth = new DateTime(1971, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "tdani18@mozilla.org",
                            FirstName = "Tod",
                            LastName = "Dani",
                            Telephone = "+46 899 360 1490"
                        },
                        new
                        {
                            Id = 46,
                            DateOfBirth = new DateTime(1981, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "abuttrey19@msu.edu",
                            FirstName = "Andie",
                            LastName = "Buttrey",
                            Telephone = "+1 159 688 7848"
                        },
                        new
                        {
                            Id = 47,
                            DateOfBirth = new DateTime(1963, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rscholer1a@answers.com",
                            FirstName = "Rozella",
                            LastName = "Scholer",
                            Telephone = "+86 586 849 1225"
                        },
                        new
                        {
                            Id = 48,
                            DateOfBirth = new DateTime(1985, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bnail1b@miibeian.gov.cn",
                            FirstName = "Beniamino",
                            LastName = "Nail",
                            Telephone = "+86 542 449 8195"
                        },
                        new
                        {
                            Id = 49,
                            DateOfBirth = new DateTime(2001, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jrieger1c@si.edu",
                            FirstName = "Jermaine",
                            LastName = "Rieger",
                            Telephone = "+380 344 492 7224"
                        },
                        new
                        {
                            Id = 50,
                            DateOfBirth = new DateTime(1967, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rstoner1d@amazonaws.com",
                            FirstName = "Ruperta",
                            LastName = "Stoner",
                            Telephone = "+967 983 679 7384"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
