// <auto-generated />
using System;
using Demo.Website.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Website.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Website.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("CURRENT_USER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(4);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1998, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rschrader0@php.net",
                            FirstName = "Raimondo",
                            LastName = "Schrader",
                            Telephone = "+449022625292"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1912, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bhilliam1@myspace.com",
                            FirstName = "Berty",
                            LastName = "Hilliam",
                            Telephone = "+449864418160"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1956, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jkonke2@bloomberg.com",
                            FirstName = "Jerrilyn",
                            LastName = "Konke",
                            Telephone = "+445517466178"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ktendahl3@spiegel.de",
                            FirstName = "Katha",
                            LastName = "Tendahl",
                            Telephone = "+446943606985"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1986, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mfritchley4@plala.or.jp",
                            FirstName = "Maurita",
                            LastName = "Fritchley",
                            Telephone = "+449675384108"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1969, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jkelcey5@angelfire.com",
                            FirstName = "Jeralee",
                            LastName = "Kelcey",
                            Telephone = "+443083415269"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1961, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hdyott6@ezinearticles.com",
                            FirstName = "Hamel",
                            LastName = "Dyott",
                            Telephone = "+441276145543"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2000, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hdorgon7@de.vu",
                            FirstName = "Harrie",
                            LastName = "Dorgon",
                            Telephone = "+442087405477"
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bheaps8@noaa.gov",
                            FirstName = "Basilio",
                            LastName = "Heaps",
                            Telephone = "+449563717412"
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1951, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lfaithfull9@rakuten.co.jp",
                            FirstName = "Lani",
                            LastName = "Faithfull",
                            Telephone = "+447062984155"
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1983, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ocharlea@ebay.com",
                            FirstName = "Oriana",
                            LastName = "Charle",
                            Telephone = "+449406044834"
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1967, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jbristerb@tamu.edu",
                            FirstName = "Jelene",
                            LastName = "Brister",
                            Telephone = ""
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1904, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nsigwardc@chronoengine.com",
                            FirstName = "Nobe",
                            LastName = "Sigward",
                            Telephone = "+443701122088"
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1969, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mbeaumand@mozilla.org",
                            FirstName = "Meta",
                            LastName = "Beauman",
                            Telephone = "+449933129156"
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1960, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "aroantreee@techcrunch.com",
                            FirstName = "Ari",
                            LastName = "Roantree",
                            Telephone = "+444461903704"
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1953, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rdowdingf@hhs.gov",
                            FirstName = "Robinett",
                            LastName = "Dowding",
                            Telephone = ""
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1903, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ajakog@example.com",
                            FirstName = "Amitie",
                            LastName = "Jako",
                            Telephone = "+444048582968"
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1950, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "fstormonthh@1688.com",
                            FirstName = "Fidelia",
                            LastName = "Stormonth",
                            Telephone = "+445624932663"
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1967, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "cgreigi@webs.com",
                            FirstName = "Chlo",
                            LastName = "Greig",
                            Telephone = "+448313967081"
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1919, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bspencersj@uol.com.br",
                            FirstName = "Beverlie",
                            LastName = "Spencers",
                            Telephone = "+442397164825"
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1950, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "cgarrattleyk@miibeian.gov.cn",
                            FirstName = "Chico",
                            LastName = "Garrattley",
                            Telephone = "+449183176571"
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1970, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ncobbinl@yale.edu",
                            FirstName = "Noak",
                            LastName = "Cobbin",
                            Telephone = "+448657697812"
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1914, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mnyssenm@sciencedirect.com",
                            FirstName = "Madalyn",
                            LastName = "Nyssen",
                            Telephone = "+444133228299"
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1921, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "agiblingn@360.cn",
                            FirstName = "Andonis",
                            LastName = "Gibling",
                            Telephone = "+447085332017"
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1933, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "gelacoateo@noaa.gov",
                            FirstName = "Gale",
                            LastName = "Elacoate",
                            Telephone = "+445774400552"
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1904, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mrisdalep@desdev.cn",
                            FirstName = "Maribel",
                            LastName = "Risdale",
                            Telephone = "+446353245719"
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1919, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ldochonq@hibu.com",
                            FirstName = "Lionel",
                            LastName = "Dochon",
                            Telephone = "+442905712109"
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1956, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "cvondrysr@wikipedia.org",
                            FirstName = "Candi",
                            LastName = "Vondrys",
                            Telephone = "+449625188471"
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1961, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hjesses@mapy.cz",
                            FirstName = "Herby",
                            LastName = "Jesse",
                            Telephone = "+445671639206"
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1901, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rmaccostyt@4shared.com",
                            FirstName = "Reinhard",
                            LastName = "MacCosty",
                            Telephone = "+449685760210"
                        },
                        new
                        {
                            Id = 31,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1979, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jpedroniu@cdc.gov",
                            FirstName = "Janice",
                            LastName = "Pedroni",
                            Telephone = "+447429061935"
                        },
                        new
                        {
                            Id = 32,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1928, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "smaroneyv@ucoz.ru",
                            FirstName = "Spense",
                            LastName = "Maroney",
                            Telephone = "+445221714877"
                        },
                        new
                        {
                            Id = 33,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1994, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ctregidgow@ca.gov",
                            FirstName = "Connie",
                            LastName = "Tregidgo",
                            Telephone = "+445863926223"
                        },
                        new
                        {
                            Id = 34,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1942, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "scretneyx@stanford.edu",
                            FirstName = "Shermie",
                            LastName = "Cretney",
                            Telephone = "+444053887430"
                        },
                        new
                        {
                            Id = 35,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1989, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mbriony@princeton.edu",
                            FirstName = "Mel",
                            LastName = "Brion",
                            Telephone = "+449451696174"
                        },
                        new
                        {
                            Id = 36,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1913, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ejannaschz@arstechnica.com",
                            FirstName = "Esta",
                            LastName = "Jannasch",
                            Telephone = "+442165300485"
                        },
                        new
                        {
                            Id = 37,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1978, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lcastangia10@economist.com",
                            FirstName = "Linc",
                            LastName = "Castangia",
                            Telephone = "+448888781806"
                        },
                        new
                        {
                            Id = 38,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hregelous11@engadget.com",
                            FirstName = "Humbert",
                            LastName = "Regelous",
                            Telephone = "+443916166178"
                        },
                        new
                        {
                            Id = 39,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1932, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kschimank12@instagram.com",
                            FirstName = "Kellen",
                            LastName = "Schimank",
                            Telephone = "+442421411499"
                        },
                        new
                        {
                            Id = 40,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1909, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ssore13@ox.ac.uk",
                            FirstName = "Sax",
                            LastName = "Sore",
                            Telephone = "+441347160893"
                        },
                        new
                        {
                            Id = 41,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1914, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "oshank14@ovh.net",
                            FirstName = "Orbadiah",
                            LastName = "Shank",
                            Telephone = "+449469784485"
                        },
                        new
                        {
                            Id = 42,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1917, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bronald15@youtu.be",
                            FirstName = "Brok",
                            LastName = "Ronald",
                            Telephone = ""
                        },
                        new
                        {
                            Id = 43,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1965, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "hbraddick16@domainmarket.com",
                            FirstName = "Hendrick",
                            LastName = "Braddick",
                            Telephone = "+447153369142"
                        },
                        new
                        {
                            Id = 44,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1913, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "glilford17@pbs.org",
                            FirstName = "Gilberto",
                            LastName = "Lilford",
                            Telephone = "+441096392236"
                        },
                        new
                        {
                            Id = 45,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1971, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "tdani18@mozilla.org",
                            FirstName = "Tod",
                            LastName = "Dani",
                            Telephone = "+448993601490"
                        },
                        new
                        {
                            Id = 46,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1981, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "abuttrey19@msu.edu",
                            FirstName = "Andie",
                            LastName = "Buttrey",
                            Telephone = "+441596887848"
                        },
                        new
                        {
                            Id = 47,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1963, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rscholer1a@answers.com",
                            FirstName = "Rozella",
                            LastName = "Scholer",
                            Telephone = "+445868491225"
                        },
                        new
                        {
                            Id = 48,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bnail1b@miibeian.gov.cn",
                            FirstName = "Beniamino",
                            LastName = "Nail",
                            Telephone = "+445424498195"
                        },
                        new
                        {
                            Id = 49,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jrieger1c@si.edu",
                            FirstName = "Jermaine",
                            LastName = "Rieger",
                            Telephone = "+443444927224"
                        },
                        new
                        {
                            Id = 50,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1967, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rstoner1d@amazonaws.com",
                            FirstName = "Ruperta",
                            LastName = "Stoner",
                            Telephone = "+449836797384"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
